---
language: java

sudo: false

script:
  - mvn test -f ./uia.utils/pom.xml
  - mvn cobertura:cobertura -f ./uia.utils/pom.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
